### ISSUE TITLE
Jedi Robe rendering

### ISSUE THREAD

**Issue by Alexismachina** [Parzivail-Modding-Team/ParziStarWarsMod#50] opened 2016-02-13 15:12 UTC
Mod Version 1.2.9
Client side
Small bug when you shit with the jedi robe it doesnt quite follow the player XD
http://i.imgur.com/y2ntgdT.png

**Comment by weastonmiller** [comment] 2016-02-13 15:36
Not a bug, something we haven't fixed yet because it's not very important and we're having to do other things, that's why these patches are still considered betas. The robe rendering and all the jedi powers will be fixed and fully added with 1.3.

**Closed by weastonmiller** 2016-02-13 15:36 UTC
